### ISSUE TITLE
About the speed and image number of LAION-5B

### ISSUE THREAD

**Issue by ImageProcessing01** [vishaal27/SuS-X#1]
Dear Sir,

I have 2 questions about retrieving the LAION-5B dataset.

1. When I use the given code to download the image URLs of LAION-5B, the obtained URL number is always smaller than the requested image number, I wonder how to solve this problem. because for some categories, I can only obtain very few image.
2. When downloading the image via the URLs, the speed is very slow, I wonder if this is normal?

And thanks for reading. Looking forward to your response.

**Comment by vishaal27** [comment]
Thanks for your interest in our work!

1. Yes, good observation -- this usually happens for somewhat rare or ambiguous categories (that do not have a lot of images that have high similarity with the given prompt). My trick to get around this is to simply increase the number of URLs requested to the clip client -- this usually lowers the image quality and correspondence to the prompt, but does the job most of the time. Since downloading the URLs is typically low cost, this trick worked well enough for my use case.
2. Yes usually it takes a while -- this is because the LAION images can be hosted on obscure URLs which can be high latency at times. Of course it totally depends on the machine you are working with, your geolocation, your internet speed etc. In my case, downloading images from 100 categories with 100 images each took about 6 hours. Therefore, I always split the download job into multiple parallel jobs, each downloading a subset of classes. This batch functionality is available in the `retrieve_images_lc_sus.py` -- simply specify the `start_index` and `end_index` of classes, and you can run the entire download job simultaneously (especially if you are working with a cluster).

Let me know if you have any other questions, thanks!

**Comment by ImageProcessing01** [comment]
Ok, thank you sir. Your answer is very useful.

**Comment by ImageProcessing01** [comment]
Btw, I find using 'import threading' can speed up the retrieving.

def fetch(url, filename):
    urlretrieve(url, filename)

try:
    filename = f"{class_store_root}/{n_valid_urls:06d}.{ext}"
    for i in range(10):
          t = threading.Thread(target=fetch, args=(url, filename))
          t.start()
except:
    continue
