### ISSUE TITLE
Confusion about the KL divergence computation in the function `get_kl_divergence_sims` in `tipx.py`

### ISSUE THREAD

**Issue by auniquesun** [vishaal27/SuS-X#8]
@vishaal27 Thanks for sharing the paper and code. It's a great work!

After the reading the code, one point confusing me is that this part in the function `get_kl_divergence_sims` in `tipx.py`

https://github.com/vishaal27/SuS-X/blob/d7d4d37881408884999fe276faacdd61b511067f/tipx.py#L29-L41

In line 33, you use `test_image_class_distribution.shape[0]//bs`. My question is when `test_image_class_distribution.shape[0]` is not an integer multiple of `bs` (e.g., `bs = 100`), does it imply setting the remaining elements to zero? What is the rationale behind doing so? It means we do not need to care the KL divergence of the remaining elelments in `test_image_class_distribution`.

It would be appreciated if you can provide some insights.

**Comment by vishaal27** [comment]
Ahh good catch, thanks for spotting that. Actually that shouldn't be the intended behaviour. I had just set batch-size to 100 for a quick iteration, and with the assumption that all test sets would be divisible by 100. It might indeed be that this is not the case. This should be relatively easy to fix, it would just need an additional iteration to compute the divergence for the residual elements.

**Comment by auniquesun** [comment]
@vishaal27  I see. Thanks for you explanation. So this operation would affect the recognition accuracy.

**Comment by vishaal27** [comment]
Hi, yes that's right. However, as you might have already noticed, this operation would only affect (test_image_class_distribution.shape[0] % 100) samples for a given dataset. Further, in essence, this bug essentially makes those predictions for those (test_image_class_distribution.shape[0] % 100) samples random---because this uniformly sets the KL-weights across all support set examples to be 0 for those particular test samples. Hence, with the fix, I expect performance to be better than what we got. Please let me know if you have any further questions regarding this / need more clarifications. Thanks!

**Comment by auniquesun** [comment]
Your explanation is aligned with my thoughts. Thanks.
